---
dist: xenial
language: ruby
rvm:
  - 2.6.0
env:
    - PATH=${HOME}/.cargo/bin:${PATH}
cache:
  directories:
    - ${HOME}/.cache/Tectonic
    - ${TRAVIS_BUILD_DIR}/vendor/bundle
    - ${HOME}/.rvm
    - ${HOME}/.cargo
    - ${HOME}/.rustup
    - ${TRAVIS_BUILD_DIR}/target
addons:
  apt:
    packages:
      - libfontconfig1-dev
      - libgraphite2-dev
      - libharfbuzz-dev
      - libicu-dev
      - libssl-dev
      - zlib1g-dev
# See https://github.com/tectonic-typesetting/tectonic/blob/master/.travis.yml
before_install:
  - |
    sudo systemctl stop apt-daily.timer &&
    sudo systemctl stop apt-daily.service &&
    sudo systemctl kill --kill-who=all apt-daily.service &&
    while ! (systemctl list-units --all apt-daily.service | fgrep -q dead) ; do
      sleep 1
    done &&
    sudo add-apt-repository -y ppa:k-peter/tectonic-ci &&
    sudo apt-get update
  - gem install bundler -v 1.17.2
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
install:
  - sudo apt-get install -y libharfbuzz-dev
  - rustup update
  - cargo install tectonic
  - bundle install --path ${TRAVIS_BUILD_DIR}/vendor/bundle
script:
  - bundle exec rake build
  - bundle exec rake spec
