---
language: ruby
rvm:
  - 2.6.0
os:
  - linux
  - osx
dist: xenial
env:
  global:
    - PATH=/home/linuxbrew/.linuxbrew/bin:${PATH}
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/target
    - ${TRAVIS_BUILD_DIR}/vendor
before_install:
  - if which brew; then brew update; else ruby -e "`curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install`" </dev/null; fi
  - gem install bundler -v 1.17.2
install:
  - brew install --only-dependencies --build-from-source tectonic
  - brew install tectonic
  - export DEP_OPENSSL_INCLUDE="$(brew --prefix openssl)/include"
  - export PKG_CONFIG_PATH="$(brew --prefix icu4c)/lib/pkgconfig"
  - export LD_LIBRARY_PATH="$(brew --prefix)/lib:${LD_LIBRARY_PATH}"
  - bundle install --path=${TRAVIS_BUILD_DIR}/vendor/bundle
script:
  - ruby --version
  - bundle exec rake build
  - bundle exec rake spec
